if(EXISTS "C:/Users/Logan/Documents/Code/math/quick-fib/release/tests/tests[1]_tests.cmake")
  include("C:/Users/Logan/Documents/Code/math/quick-fib/release/tests/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
